USE LONJA_LRM

CREATE TABLE [dbo].[Clientes](
	[ID_Cliente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Apellidos] [varchar](50) NULL,
	[Fecha_nac] [datetime] NULL,
	[DNI] [varchar](10) NULL,
	[DNI_Encrypted] [varbinary](128) NULL
)
GO

GO
USE MASTER
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD ='abc123.';
GO

CREATE CERTIFICATE BackupCert
WITH SUBJECT = 'MI CERTIFICADO TDE'
GO

SELECT * FROM
sys.certificates

USE LONJA_LRM
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE BackupCert
GO

USE master
GO


BACKUP DATABASE LONJA_LRM
TO DISK = 'C:\TEMP\LONJA_LRM_TDE.bak'
WITH ENCRYPTION
(
ALGORITHM = AES_256,
SERVER CERTIFICATE = BackupCert
),
STATS = 10

--- GUARDAR CERTIFICADO
BACKUP CERTIFICATE BackupCert
	TO FILE = 'C:\TEMP\BackupCert'
	WITH PRIVATE KEY
	(
	FILE = 'C:\TEMP\BackupCert.pvk',
	ENCRYPTION BY PASSWORD = 'abc123.')
GO